### ISSUE TITLE
QoS always 'AtMostOnce'

### ISSUE THREAD

**Issue by kblyr** [SeppPenner/MQTTnet.TestApp.WinForm#4]
I'm trying this sample app, I tried changing the QoS level the publisher is sending, I changed it to AtleastOnce/ExactlyOnce, but the subscriber always indicates that the QoS is 'AtMostOnce'... And the subscriber can't get the the messages sent when it is offline

**Comment by SeppPenner** [comment]
I'm not sure what exactly is the issue here, but my test subscriber using mqtt.fx as second client (http://www.mqttfx.jensd.de/) can get the messages when connecting.

However, you seem to be right, the QoS level is always set to `AtMostOnce`. I have no idea, this must be either intended or an issue with the main library used, https://github.com/chkr1011/MQTTnet... Maybe, the server handles retained messages always as QoS level 0? I'm not that deep into the internals of MqttNet, but you probably should ask someone from the main developers at https://github.com/chkr1011/MQTTnet/issues...
